default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: league30_development

test:
  <<: *default
  database: league30_test

production:
  <<: *default
  database: league30_production
